/**
 * Scheduling Profile — Factory-Backed Stories
 *
 * Demonstrates the scheduling-profile component using mocksEngine-generated
 * tournament data, TemporalEngine-backed adapters, and the full round-trip
 * to scheduleProfileRounds().
 *
 * Stories:
 * - FactoryBacked: Basic rendering with real factory data
 * - RoundTrip: Authoring → scheduleProfileRounds() cycle
 * - CapacityAware: Oversubscription detection with real court-hours
 * - PreScheduled: Pre-populated profile from programmatic distribution
 */

import 'tippy.js/dist/tippy.css';

import { tournamentEngine, temporal } from 'tods-competition-factory';

import {
  SchedulingProfileControl,
  createSchedulingProfile,
} from '../../components/scheduling-profile';

import type { SchedulingProfile } from '../../components/scheduling-profile';

import {
  createFactorySetup,
  profileToFactoryFormat,
  buildHeavyProfile,
  buildSpreadProfile,
} from './factoryData';

const { calculateCapacityStats } = temporal;

export default {
  title: 'Scheduling Profile/Factory',
  parameters: {
    layout: 'fullscreen',
    backgrounds: { default: 'dark' },
  },
};

// ── Shared Styles ────────────────────────────────────────────────────────────

const ROOT_STYLE =
  'background: var(--sp-bg); min-height: 100vh;';

const INFO_STYLE =
  'font-size: 12px; color: var(--sp-muted); padding: 12px 16px; font-family: ui-sans-serif, system-ui, sans-serif;';

const BTN_STYLE =
  'padding: 6px 12px; border-radius: 8px; border: 1px solid var(--sp-accent-border); background: var(--sp-selected-bg); color: var(--sp-text); cursor: pointer; font-size: 12px;';

const BTN_STYLE_OK =
  'padding: 6px 12px; border-radius: 8px; border: 1px solid var(--sp-ok-border); background: var(--sp-selected-bg); color: var(--sp-text); cursor: pointer; font-size: 12px;';

const FOOTER_STYLE =
  'padding: 12px 16px; border-top: 1px solid var(--sp-line); font-size: 12px; color: var(--sp-muted); font-family: ui-sans-serif, system-ui, sans-serif; display: flex; gap: 12px; align-items: center; flex-wrap: wrap;';

const PRE_STYLE =
  'margin: 0; padding: 12px 16px; background: var(--sp-card-bg); border-top: 1px solid var(--sp-line); color: var(--sp-muted); font-size: 11px; font-family: ui-monospace, monospace; max-height: 200px; overflow: auto; white-space: pre-wrap;';

// ── Helpers ──────────────────────────────────────────────────────────────────

function addConsoleLog(container: HTMLElement, control: SchedulingProfileControl): void {
  const footer = document.createElement('div');
  footer.style.cssText = FOOTER_STYLE;

  const exportBtn = document.createElement('button');
  exportBtn.textContent = 'Export Profile (console)';
  exportBtn.style.cssText = BTN_STYLE;
  exportBtn.addEventListener('click', () => {
    const profile = control.getProfile();
    console.log('Scheduling Profile:', JSON.stringify(profile, null, 2));
    const state = control.getStore().getState();
    statusEl.textContent = `Exported! ${state.issueIndex.counts.total} issues (${state.issueIndex.counts.ERROR} errors). See browser console.`;
  });

  const statusEl = document.createElement('span');
  statusEl.textContent = 'Drag rounds from the catalog (right) to a venue lane (center).';

  footer.appendChild(exportBtn);
  footer.appendChild(statusEl);
  container.appendChild(footer);
}

// ============================================================================
// Story A: FactoryBacked
// ============================================================================

export const FactoryBacked = {
  render: () => {
    const root = document.createElement('div');
    root.style.cssText = ROOT_STYLE;

    const setup = createFactorySetup();

    // Info banner
    const info = document.createElement('div');
    info.style.cssText = INFO_STYLE;
    info.innerHTML = [
      '<strong>Factory-Backed</strong> &mdash; Tournament generated by mocksEngine with',
      `${setup.roundCatalog.length} rounds across`,
      `${new Set(setup.roundCatalog.map((r) => r.eventId)).size} events,`,
      `${setup.venues.length} venues,`,
      `TemporalEngine-backed availability.`,
      `Date range: ${setup.startDate} to ${setup.endDate}.`,
    ].join(' ');
    root.appendChild(info);

    // Component container
    const container = document.createElement('div');
    root.appendChild(container);

    const control = createSchedulingProfile(
      {
        ...setup.config,
        onProfileChanged: (profile) => {
          const totalRounds = profile.reduce(
            (sum, day) => sum + day.venues.reduce((vs, v) => vs + v.rounds.length, 0),
            0,
          );
          console.log(`Profile changed: ${totalRounds} rounds placed`);
        },
      },
      container,
    );

    // Footer with stats
    const footer = document.createElement('div');
    footer.style.cssText = FOOTER_STYLE;

    const statsText = [
      `Rounds: ${setup.roundCatalog.length}`,
      `Events: ${new Set(setup.roundCatalog.map((r) => r.eventId)).size}`,
      `Venues: ${setup.venues.length}`,
      `Dates: ${setup.schedulableDates.length} (${setup.startDate} \u2192 ${setup.endDate})`,
      `Tournament: ${setup.tournamentId.slice(0, 8)}\u2026`,
    ].join(' \u2502 ');

    const statsEl = document.createElement('span');
    statsEl.textContent = statsText;
    footer.appendChild(statsEl);
    root.appendChild(footer);

    addConsoleLog(root, control);
    return root;
  },
};

// ============================================================================
// Story B: RoundTrip
// ============================================================================

export const RoundTrip = {
  render: () => {
    const root = document.createElement('div');
    root.style.cssText = ROOT_STYLE;

    const setup = createFactorySetup();

    // Info banner
    const info = document.createElement('div');
    info.style.cssText = INFO_STYLE;
    info.innerHTML = [
      '<strong>Round-Trip</strong> &mdash; Place rounds in the profile, then click',
      '"Schedule Profile Rounds" to run the factory scheduler.',
      'Results appear in the panel below.',
    ].join(' ');
    root.appendChild(info);

    // Component container
    const container = document.createElement('div');
    root.appendChild(container);

    const control = createSchedulingProfile(setup.config, container);

    // Action bar
    const actionBar = document.createElement('div');
    actionBar.style.cssText = FOOTER_STYLE;

    const scheduleBtn = document.createElement('button');
    scheduleBtn.textContent = 'Schedule Profile Rounds';
    scheduleBtn.style.cssText = BTN_STYLE_OK;

    const resultPanel = document.createElement('pre');
    resultPanel.style.cssText = PRE_STYLE;
    resultPanel.textContent = 'Place rounds in the profile above, then click "Schedule Profile Rounds".';

    scheduleBtn.addEventListener('click', () => {
      const profile = control.getProfile();
      const factoryProfile = profileToFactoryFormat(profile);

      // Set the scheduling profile on the tournament
      tournamentEngine.setState(setup.tournamentRecord);
      const setResult = tournamentEngine.setSchedulingProfile({
        schedulingProfile: factoryProfile,
      });

      if (setResult?.error) {
        resultPanel.textContent = `setSchedulingProfile error: ${JSON.stringify(setResult.error, null, 2)}`;
        return;
      }

      // Run the scheduler
      const scheduleDates = profile.map((d) => d.scheduleDate);
      const scheduleResult = tournamentEngine.scheduleProfileRounds({ scheduleDates });

      // Display results
      const lines: string[] = ['=== Schedule Profile Rounds Result ===', ''];

      if (scheduleResult?.error) {
        lines.push(`Error: ${JSON.stringify(scheduleResult.error)}`);
      } else {
        const scheduledIds = scheduleResult?.scheduledMatchUpIds || {};
        const overLimitIds = scheduleResult?.overLimitMatchUpIds || {};
        const scheduledDates = scheduleResult?.scheduledDates || [];

        let totalScheduled = 0;
        for (const ids of Object.values(scheduledIds)) {
          totalScheduled += (ids as string[]).length;
        }

        let totalOverLimit = 0;
        for (const ids of Object.values(overLimitIds)) {
          totalOverLimit += (ids as string[]).length;
        }

        lines.push(`Scheduled dates: ${scheduledDates.join(', ') || '(none)'}`);
        lines.push(`Total matchUps scheduled: ${totalScheduled}`);
        lines.push(`Over-limit matchUps: ${totalOverLimit}`);
        lines.push('');

        if (Object.keys(scheduledIds).length > 0) {
          lines.push('Scheduled by date:');
          for (const [date, ids] of Object.entries(scheduledIds)) {
            lines.push(`  ${date}: ${(ids as string[]).length} matchUps`);
          }
        }

        if (totalOverLimit > 0) {
          lines.push('');
          lines.push('Over-limit by date:');
          for (const [date, ids] of Object.entries(overLimitIds)) {
            if ((ids as string[]).length > 0) {
              lines.push(`  ${date}: ${(ids as string[]).length} matchUps`);
            }
          }
        }
      }

      resultPanel.textContent = lines.join('\n');
      console.log('scheduleProfileRounds result:', scheduleResult);
    });

    actionBar.appendChild(scheduleBtn);
    root.appendChild(actionBar);
    root.appendChild(resultPanel);

    addConsoleLog(root, control);
    return root;
  },
};

// ============================================================================
// Story C: CapacityAware
// ============================================================================

export const CapacityAware = {
  render: () => {
    const root = document.createElement('div');
    root.style.cssText = ROOT_STYLE;

    const setup = createFactorySetup({ includeBookings: true });
    const heavyProfile = buildHeavyProfile(setup);

    // Info banner
    const info = document.createElement('div');
    info.style.cssText = INFO_STYLE;
    info.innerHTML = [
      '<strong>Capacity-Aware</strong> &mdash; Day 1 is overloaded with many rounds at one venue.',
      'Court bookings (maintenance + practice) reduce available capacity.',
      'The capacity panel below updates in real-time as you add/remove rounds.',
    ].join(' ');
    root.appendChild(info);

    // Component container
    const container = document.createElement('div');
    root.appendChild(container);

    // Capacity panel
    const capacityPanel = document.createElement('pre');
    capacityPanel.style.cssText = PRE_STYLE;

    function updateCapacityPanel(profile: SchedulingProfile): void {
      const lines: string[] = ['=== Per-Day Capacity vs Demand ===', ''];

      for (const date of setup.schedulableDates) {
        const capacityMinutes = setup.temporalAdapter.getDayCapacityMinutes?.(date) ?? 0;
        const demandMinutes = setup.demandAdapter.estimateDayDemandMinutes(date, profile);
        const ratio = capacityMinutes > 0 ? Math.round((demandMinutes / capacityMinutes) * 100) : 0;
        const status = demandMinutes === 0 ? 'EMPTY' : ratio > 100 ? 'OVERLOADED' : 'OK';

        lines.push(
          `${date}: ${demandMinutes}min demand / ${capacityMinutes}min capacity (${ratio}%) [${status}]`,
        );
      }

      // Engine-level stats for day 1
      lines.push('');
      lines.push('--- Engine Capacity Details (Day 1) ---');
      const curve = setup.engine.getCapacityCurve(setup.startDate);
      const stats = calculateCapacityStats(curve);
      lines.push(`Total court-hours: ${stats.totalCourtHours.toFixed(1)}`);
      lines.push(`Available court-hours: ${(stats.totalAvailableHours ?? 0).toFixed(1)}`);
      lines.push(`Utilization: ${stats.utilizationPercent.toFixed(1)}%`);
      lines.push(`Peak available courts: ${stats.peakAvailable}`);

      capacityPanel.textContent = lines.join('\n');
    }

    // Initial render with heavy profile
    updateCapacityPanel(heavyProfile);

    const control = createSchedulingProfile(
      {
        ...setup.config,
        initialProfile: heavyProfile,
        onProfileChanged: (profile) => {
          updateCapacityPanel(profile);
        },
      },
      container,
    );

    root.appendChild(capacityPanel);
    addConsoleLog(root, control);
    return root;
  },
};

// ============================================================================
// Story D: PreScheduled
// ============================================================================

export const PreScheduled = {
  render: () => {
    const root = document.createElement('div');
    root.style.cssText = ROOT_STYLE;

    const setup = createFactorySetup();
    const spreadProfile = buildSpreadProfile(setup);

    // Optionally run factory scheduler to set times
    tournamentEngine.setState(setup.tournamentRecord);
    const factoryProfile = profileToFactoryFormat(spreadProfile);
    const setResult = tournamentEngine.setSchedulingProfile({
      schedulingProfile: factoryProfile,
    });

    let schedulerInfo = '';
    if (!setResult?.error) {
      const scheduleDates = spreadProfile.map((d) => d.scheduleDate);
      const scheduleResult = tournamentEngine.scheduleProfileRounds({ scheduleDates });
      const scheduledIds = scheduleResult?.scheduledMatchUpIds || {};
      let totalScheduled = 0;
      for (const ids of Object.values(scheduledIds)) {
        totalScheduled += (ids as string[]).length;
      }
      schedulerInfo = ` Factory scheduled ${totalScheduled} matchUps across ${(scheduleResult?.scheduledDates || []).length} dates.`;
    }

    // Info banner
    const info = document.createElement('div');
    info.style.cssText = INFO_STYLE;
    info.innerHTML = [
      '<strong>Pre-Scheduled</strong> &mdash; Rounds are pre-distributed across dates',
      'respecting round-number precedence.',
      schedulerInfo,
      'Review the distribution and adjust as needed.',
    ].join(' ');
    root.appendChild(info);

    // Component container
    const container = document.createElement('div');
    root.appendChild(container);

    const control = createSchedulingProfile(
      {
        ...setup.config,
        initialProfile: spreadProfile,
        onProfileChanged: (profile) => {
          const totalRounds = profile.reduce(
            (sum, day) => sum + day.venues.reduce((vs, v) => vs + v.rounds.length, 0),
            0,
          );
          console.log(`Profile changed: ${totalRounds} rounds placed`);
        },
      },
      container,
    );

    addConsoleLog(root, control);
    return root;
  },
};

// ============================================================================
// Story E: FullHeight
// ============================================================================

export const FullHeight = {
  render: () => {
    const root = document.createElement('div');
    root.style.cssText = 'background: var(--sp-bg); height: 100vh; overflow: hidden;';

    const setup = createFactorySetup();
    createSchedulingProfile(setup.config, root);

    return root;
  },
};

// ============================================================================
// Story F: ManyVenues — Horizontal scroll when venues exceed threshold
// ============================================================================

function venueCountStory(venueCount: number) {
  return {
    render: () => {
      const root = document.createElement('div');
      root.style.cssText = ROOT_STYLE;

      const setup = createFactorySetup({ venueCount });

      const info = document.createElement('div');
      info.style.cssText = INFO_STYLE;
      info.innerHTML = [
        `<strong>${venueCount} Venues</strong> &mdash;`,
        venueCount > 4
          ? 'Day Plan scrolls horizontally (min 240px per venue column).'
          : 'Venues fit within the available width.',
        `${setup.roundCatalog.length} rounds across ${setup.venues.length} venues.`,
      ].join(' ');
      root.appendChild(info);

      const container = document.createElement('div');
      root.appendChild(container);

      const control = createSchedulingProfile(setup.config, container);
      addConsoleLog(root, control);

      return root;
    },
  };
}

export const Venues3 = venueCountStory(3);
export const Venues6 = venueCountStory(6);
export const Venues10 = venueCountStory(10);
