/**
 * Core data types for the Temporal Resource Engine
 * 
 * Following the principle: "Time as a First-Class Object"
 * Courts are modeled as continuous time-based capacity streams, not static assets.
 */

// ============================================================================
// Time & Identity Primitives
// ============================================================================

export type DayId = string; // 'YYYY-MM-DD'
export type BlockId = string;
export type FacilityId = string;
export type CourtId = string;
export type TournamentId = string;
export type TemplateId = string;
export type RuleId = string;

// ============================================================================
// Block Types & Semantics
// ============================================================================

/**
 * BlockType defines the semantic meaning of a time segment.
 * Precedence matters for overlapping blocks (defined in EngineConfig).
 */
export type BlockType =
  | 'AVAILABLE' // Court is available for scheduling
  | 'BLOCKED' // Generic block (reason specified)
  | 'PRACTICE' // Reserved for practice
  | 'MAINTENANCE' // Maintenance window
  | 'RESERVED' // Reserved for specific purpose
  | 'SOFT_BLOCK' // Can be overridden if needed
  | 'HARD_BLOCK' // Cannot be overridden
  | 'LOCKED' // System-locked, no user modification
  | 'UNSPECIFIED'; // No explicit status (gray fog)

export type BlockSource = 'USER' | 'TEMPLATE' | 'RULE' | 'SYSTEM';
export type BlockHardness = 'HARD' | 'SOFT';

// ============================================================================
// Time Ranges & Court References
// ============================================================================

export interface TimeRange {
  start: string; // ISO 8601 datetime string (e.g., '2026-06-15T08:00:00')
  end: string; // ISO 8601 datetime string
}

export interface CourtRef {
  tournamentId: TournamentId;
  facilityId: FacilityId;
  courtId: CourtId;
}

// ============================================================================
// Blocks (Raw Storage)
// ============================================================================

/**
 * Block represents a user-defined or system-generated time constraint
 * on a court. Blocks are the only "authoritative" objects; all other
 * structures (rails, capacity curves) are derived from blocks.
 */
export interface Block extends TimeRange {
  id: BlockId;
  court: CourtRef;
  type: BlockType;
  reason?: string; // Human-readable reason for the block
  priority?: number; // Higher priority wins in conflicts
  hardSoft?: BlockHardness;
  recurrenceKey?: string; // Link to template/recurrence pattern
  source?: BlockSource;
}

// ============================================================================
// Derived Rail Segments (Computed)
// ============================================================================

/**
 * RailSegment is a derived, non-overlapping time segment on a court.
 * Generated by the rail derivation algorithm from overlapping blocks.
 */
export interface RailSegment extends TimeRange {
  status: BlockType; // Effective semantic status for this segment
  contributingBlocks: BlockId[]; // Blocks that contribute to this segment
}

/**
 * CourtRail represents the continuous timeline for a single court on a day.
 */
export interface CourtRail {
  court: CourtRef;
  segments: RailSegment[]; // Non-overlapping, sorted by start time
}

/**
 * FacilityDayTimeline represents all courts in a facility for a single day.
 */
export interface FacilityDayTimeline {
  day: DayId;
  facilityId: FacilityId;
  rails: CourtRail[];
}

// ============================================================================
// Capacity Curves
// ============================================================================

/**
 * CapacityPoint represents the number of courts in various states
 * at a specific point in time.
 */
export interface CapacityPoint {
  time: string; // ISO 8601 datetime
  courtsAvailable: number;
  courtsSoftBlocked: number;
  courtsHardBlocked: number;
}

/**
 * CapacityCurve is a time-series view of court capacity for a day.
 */
export interface CapacityCurve {
  day: DayId;
  points: CapacityPoint[];
}

// ============================================================================
// Templates & Rules
// ============================================================================

export interface Template {
  id: TemplateId;
  name: string;
  description?: string;
  operations: TemplateOperation[];
}

export interface TemplateOperation {
  target: 'TOURNAMENT' | 'FACILITY' | 'COURT_GROUP' | 'COURT';
  facilityIds?: FacilityId[];
  courtIds?: CourtId[];
  days?: DayId[];
  relativeTime?: {
    startOffsetMinutes: number;
    endOffsetMinutes: number;
  };
  absoluteTime?: TimeRange;
  blockType: BlockType;
  reason?: string;
  hardSoft?: BlockHardness;
}

export interface Rule {
  id: RuleId;
  name: string;
  description?: string;
  // Rules are evaluated functions that return block mutations
  evaluate: (ctx: EngineContext) => BlockMutation[];
}

// ============================================================================
// Mutations & Results
// ============================================================================

export type MutationKind = 'ADD_BLOCK' | 'UPDATE_BLOCK' | 'REMOVE_BLOCK';

export interface BlockMutation {
  kind: MutationKind;
  block: Block;
  previousBlock?: Block; // For UPDATE_BLOCK, store the old version
}

export interface MutationResult {
  applied: BlockMutation[];
  rejected: BlockMutation[];
  warnings: EngineWarning[];
  conflicts: EngineConflict[];
}

export interface SimulationResult {
  previewRails: FacilityDayTimeline[];
  capacityImpact?: CapacityCurve;
  conflicts: EngineConflict[];
}

// ============================================================================
// Warnings & Conflicts
// ============================================================================

export type ConflictSeverity = 'INFO' | 'WARN' | 'ERROR';

export interface EngineWarning {
  code: string;
  message: string;
  relatedBlocks?: BlockId[];
  relatedCourts?: CourtRef[];
}

export interface EngineConflict {
  code: string;
  message: string;
  severity: ConflictSeverity;
  timeRange: TimeRange;
  courts: CourtRef[];
  relatedMatches?: string[]; // TODS matchUp IDs for "shadow scheduling"
}

// ============================================================================
// Engine Configuration
// ============================================================================

export interface EngineConfig {
  tournamentId: TournamentId;
  dayStartTime: string; // 'HH:MM' (e.g., '06:00')
  dayEndTime: string; // 'HH:MM' (e.g., '23:00')
  slotMinutes: number; // Granularity for rendering (5, 10, 15)
  
  /**
   * Type precedence for resolving overlapping blocks.
   * First type in array has highest priority.
   * Example: ['HARD_BLOCK', 'LOCKED', 'MAINTENANCE', 'PRACTICE', 'SOFT_BLOCK', 'AVAILABLE']
   */
  typePrecedence: BlockType[];
  
  /**
   * Pluggable conflict evaluators
   */
  conflictEvaluators?: ConflictEvaluator[];
}

export interface ConflictEvaluator {
  id: string;
  description: string;
  evaluate: (ctx: EngineContext, mutations: BlockMutation[]) => EngineConflict[];
}

// ============================================================================
// Engine Context (Internal State Snapshot)
// ============================================================================

export interface EngineContext {
  config: EngineConfig;
  tournamentRecord: any; // TODS tournamentRecord
  
  // Internal indices
  blocksById: Map<BlockId, Block>;
  blocksByCourtDay: Map<string, BlockId[]>; // Key: courtDayKey(court, day)
  
  templates: Map<TemplateId, Template>;
  rules: Map<RuleId, Rule>;
  
  // Current view state
  selectedDay?: DayId;
  selectedFacility?: FacilityId;
  selectedCourt?: CourtId;
  layerVisibility: Map<BlockType, boolean>;
}

// ============================================================================
// Engine Events
// ============================================================================

export type EngineEventType =
  | 'STATE_CHANGED'
  | 'BLOCKS_CHANGED'
  | 'CONFLICTS_CHANGED'
  | 'VIEW_CHANGED';

export interface EngineEvent {
  type: EngineEventType;
  payload: any;
}

export interface StateChangedEvent extends EngineEvent {
  type: 'STATE_CHANGED';
  payload: {
    reason: string;
  };
}

export interface BlocksChangedEvent extends EngineEvent {
  type: 'BLOCKS_CHANGED';
  payload: {
    mutations: BlockMutation[];
  };
}

export interface ConflictsChangedEvent extends EngineEvent {
  type: 'CONFLICTS_CHANGED';
  payload: {
    conflicts: EngineConflict[];
  };
}

export interface ViewChangedEvent extends EngineEvent {
  type: 'VIEW_CHANGED';
  payload: {
    day?: DayId;
    facilityId?: FacilityId | null;
    courtId?: CourtId | null;
  };
}

// ============================================================================
// Command Options
// ============================================================================

export interface ApplyBlockOptions {
  courts: CourtRef[];
  timeRange: TimeRange;
  type: BlockType;
  reason?: string;
  hardSoft?: BlockHardness;
  source?: BlockSource;
}

export interface MoveBlockOptions {
  blockId: BlockId;
  newTimeRange: TimeRange;
  newCourt?: CourtRef;
}

export interface ResizeBlockOptions {
  blockId: BlockId;
  newTimeRange: TimeRange;
}

export interface ApplyTemplateOptions {
  templateId: TemplateId;
  scope?: {
    facilities?: FacilityId[];
    courts?: CourtRef[];
    days?: DayId[];
  };
}

// ============================================================================
// Court Metadata (for UI projections)
// ============================================================================

export interface CourtMeta {
  ref: CourtRef;
  name: string;
  surface: string;
  indoor: boolean;
  hasLights: boolean;
  tags: string[];
  extendedProps?: Record<string, any>; // Additional TODS properties
}

// ============================================================================
// Utility Types
// ============================================================================

/**
 * Edge used in sweep-line algorithm for rail derivation
 */
export interface Edge {
  time: string;
  type: 'START' | 'END';
  blockId: BlockId;
}
