import './composition-editor.css';

export const ceLayout = () => 'ce-layout';
export const ceLeft = () => 'ce-left';
export const ceRight = () => 'ce-right';
export const ceNameRow = () => 'ce-name-row';
export const ceNameLabel = () => 'ce-name-label';
export const ceNameInput = () => 'ce-name-input';
export const ceSection = () => 'ce-section';
export const ceSectionHeader = () => 'ce-section-header';
export const ceSectionChevron = () => 'ce-section-chevron';
export const ceSectionBody = () => 'ce-section-body';
export const ceField = () => 'ce-field';
export const ceFieldLabel = () => 'ce-field-label';
export const ceFieldControl = () => 'ce-field-control';
export const ceSelect = () => 'ce-select';
export const ceTextInput = () => 'ce-text-input';
export const ceColorInput = () => 'ce-color-input';
export const ceToggle = () => 'ce-toggle';
export const ceToggleTrack = () => 'ce-toggle-track';
export const cePreview = () => 'ce-preview';
export const cePreviewHeader = () => 'ce-preview-header';
export const cePreviewBody = () => 'ce-preview-body';
export const cePreviewMatchup = () => 'ce-preview-matchup';
export const cePresetRow = () => 'ce-preset-row';
export const cePresetLabel = () => 'ce-preset-label';
export const ceSubgroup = () => 'ce-subgroup';
export const ceSubgroupTitle = () => 'ce-subgroup-title';
